{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e4593038-3221-4612-91de-9ff6e0411dab",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Import the market research dataset\n",
    "\n",
    "file_path21 = r\"LPWA_global.xlsx\"\n",
    "file_path22 = r\"LPWA_EU.xlsx\"\n",
    "file_path23 = r\"Mobile_global.xlsx\"\n",
    "file_path24 = r\"Mobile_EU.xlsx\"\n",
    "file_path25 = r\"Satellite_global.xlsx\"\n",
    "file_path26 = r\"Satellite_EU.xlsx\"\n",
    "\n",
    "try:\n",
    "    df_LPWA_global = pd.read_excel(file_path21)\n",
    "#    print(\"Market Research data loaded successfully. Here are the first few rows:\")\n",
    "#    print(df.head())\n",
    "    data_types_df = df_LPWA_global.dtypes\n",
    "#    print(data_types_df)\n",
    "except Exception as e:\n",
    "    print(\"An error occurred while loading the file:\", e)\n",
    "\n",
    "try:\n",
    "    df_LPWA_EU = pd.read_excel(file_path22)\n",
    "#    print(\"Market Research data loaded successfully. Here are the first few rows:\")\n",
    "#    print(df.head())\n",
    "    data_types_df = df_LPWA_EU.dtypes\n",
    "#    print(data_types_df)\n",
    "except Exception as e:\n",
    "    print(\"An error occurred while loading the file:\", e)\n",
    "    \n",
    "try:\n",
    "    df_Mobile_global = pd.read_excel(file_path23)\n",
    "#    print(\"Market Research data loaded successfully. Here are the first few rows:\")\n",
    "#    print(df.head())\n",
    "    data_types_df = df_Mobile_global.dtypes\n",
    "#    print(data_types_df)\n",
    "except Exception as e:\n",
    "    print(\"An error occurred while loading the file:\", e)\n",
    "\n",
    "\n",
    "try:\n",
    "    df_Mobile_EU = pd.read_excel(file_path24)\n",
    "#    print(\"Market Research data loaded successfully. Here are the first few rows:\")\n",
    "#    print(df.head())\n",
    "    data_types_df = df_Mobile_EU.dtypes\n",
    "#    print(data_types_df)\n",
    "except Exception as e:\n",
    "    print(\"An error occurred while loading the file:\", e)\n",
    "\n",
    "try:\n",
    "    df_Satellite_global = pd.read_excel(file_path25)\n",
    "#    print(\"Market Research data loaded successfully. Here are the first few rows:\")\n",
    "#    print(df.head())\n",
    "    data_types_df = df_Satellite_global.dtypes\n",
    "#    print(data_types_df)\n",
    "except Exception as e:\n",
    "    print(\"An error occurred while loading the file:\", e)\n",
    "\n",
    "try:\n",
    "    df_Satellite_EU = pd.read_excel(file_path26)\n",
    "#    print(\"Market Research data loaded successfully. Here are the first few rows:\")\n",
    "#    print(df.head())\n",
    "    data_types_df = df_Satellite_EU.dtypes\n",
    "#    print(data_types_df)\n",
    "except Exception as e:\n",
    "    print(\"An error occurred while loading the file:\", e)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
